<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-SistemaMatriculaUniversitaria-f0574dfe-c887-4aea-b367-ef497bf37fa5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.15" />
  </ItemGroup>

</Project>
